#include "ANSI.h"

/* Definitions for the constants contained in ANSI::TERMINAL */

const char * ANSI::TERMINAL::FOREGROUND::BLACK = "\33[30m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_RED = "\33[31m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_GREEN = "\33[32m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_YELLOW = "\33[33m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_BLUE = "\33[34m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_PURPLE ="\33[35m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_CYAN = "\33[36m";
const char * ANSI::TERMINAL::FOREGROUND::LIGHT_GREY = "\33[37m";
const char * ANSI::TERMINAL::FOREGROUND::DARK_GREY = "\33[90m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_RED = "\33[91m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_GREEN = "\33[92m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_YELLOW = "\33[93m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_BLUE = "\33[94m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_PURPLE = "\33[95m";
const char * ANSI::TERMINAL::FOREGROUND::BRIGHT_CYAN = "\33[96m";
const char * ANSI::TERMINAL::FOREGROUND::WHITE = "\33[97m";

const char * ANSI::TERMINAL::BACKGROUND::BLACK = "\33[40m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_RED = "\33[41m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_GREEN = "\33[42m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_YELLOW = "\33[43m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_BLUE = "\33[44m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_PURPLE ="\33[45m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_CYAN = "\33[46m";
const char * ANSI::TERMINAL::BACKGROUND::LIGHT_GREY = "\33[47m";
const char * ANSI::TERMINAL::BACKGROUND::DARK_GREY = "\33[100m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_RED = "\33[101m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_GREEN = "\33[102m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_YELLOW = "\33[103m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_BLUE = "\33[104m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_PURPLE = "\33[105m";
const char * ANSI::TERMINAL::BACKGROUND::BRIGHT_CYAN = "\33[106m";
const char * ANSI::TERMINAL::BACKGROUND::WHITE = "\33[107m";

/* ANSI Terminal Format codes */
const char * ANSI::TERMINAL::RESET = "\33[0m";
const char * ANSI::TERMINAL::BOLD = "\33[1m";
const char * ANSI::TERMINAL::UNDERLINE = "\33[4m";
const char * ANSI::TERMINAL::INVERSE = "\33[7m";
const char * ANSI::TERMINAL::BOLD_OFF = "\33[21m";
const char * ANSI::TERMINAL::UNDERLINE_OFF = "\33[24m";
const char * ANSI::TERMINAL::INVERSE_OFF = "\33[27m";